
<?php

$shortenedUrlForm = $this->shortenedUrlForm;

$shortenedUrlForm->getAttributes([
    'class'=>'form-control needs-validation novalidate',
    'style'=>'display:contents'
]);

$descriptionElement = $shortenedUrlForm->get('description');
$fullUrlElement = $shortenedUrlForm->get('full-url');
$shortenedUrlElement = $shortenedUrlForm->get('shortened-url');
$commentsElement = $shortenedUrlForm->get('comments');

$csrfElement = $shortenedUrlForm->get('shortened_url_csrf');

if($this->scenario == "edit"){

    $user = $this->user;

    $fullUrlElement->setValue( $this->shortenedUrl->getShortnedUrl());
    $shortenedUrlElement->setValue( $this->shortenedUrl->getShortnedUrl());
}

$submitElement = $shortenedUrlForm->get('shortened-url-submit');
$shortenedUrlForm->prepare();

?>

<div class="w-full">
    <div class="mx-auto px-0 w-full">
        <?php include __DIR__ . '/../../partials/top_nav_bar_menu_logged_out.phtml'; ?>
    </div>
</div>
<div class="flex">
    <!-- dashboard -->
    <?php
    include __DIR__.'/../../partials/user_sidebar_dashboard.phtml';
    ?>
    <div class="flex-1">
    <div class="min-h-screen  items-center justify-center mt-10">
        <div class="w-full max-w-3xl mx-auto bg-white rounded-lg shadow-lg p-6">
            <h2 class="text-2xl font-bold mb-4 text-center text-gray-900">Create: URL Shortener Form</h2>

            <?php
            if($this->messageType ="error")
                $messages = $this->messages;
            $generalError = 'There are error message(s) please check respective fields below, correct and resubmit the form.';
            if (!empty($messages)):?>

                <div class="mb-4 p-4 text-red-700 bg-red-100 border border-red-400 rounded">
                    <?= htmlspecialchars($generalError, ENT_QUOTES, 'UTF-8') ?>
                </div>

                <?php if (isset($messages['shortened_url_csrf'])): ?>
                <div class="mb-4 p-4 text-red-700 bg-red-100 border border-red-400 rounded">
                    <?= htmlspecialchars(implode(', ', $messages['shortened_url_csrf']), ENT_QUOTES, 'UTF-8') ?>
                </div>

                <?php endif; ?>

            <?php endif; ?>

            <?= $this->form()->openTag($shortenedUrlForm); ?>

            <div class="form-control mb-4">
                <?php
                $descriptionElement->setLabelAttributes(['class' => 'label label-text text-gray-600']);
                $descriptionElement->setLabel('Short Description')
                    ->setAttributes([
                        'class' => 'input input-bordered w-full placeholder-gray-500 placeholder:text-sm',
                        'placeholder' => 'Enter Shortened Url'
                    ]);
                echo $this->formLabel($descriptionElement, $descriptionElement->getLabel());
                ?>
                <?=
                $this->formElement($descriptionElement);
                ?>
                <!-- Invalid description Errors-->
                <?php if (isset($messages['description'])): ?>
                    <div class="text-red-600 mt-2 text-sm">
                        <?= htmlspecialchars(implode(', ', $messages['description']), ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="form-control mb-4">
               <?php
                $fullUrlElement->setLabelAttributes(['class' => 'label label-text text-gray-600']);
                $fullUrlElement->setLabel('Full URL')
                    ->setAttributes([
                        'class' => 'input input-bordered w-full placeholder-gray-500 placeholder:text-sm',
                        'placeholder' => 'Enter Full URL'
                    ]);
                echo $this->formLabel($fullUrlElement, $fullUrlElement->getLabel());
                ?>
                <?=
                $this->formElement($fullUrlElement);
                ?>
                <!-- Invalid full-url Errors-->
                <?php if (isset($messages['full-url'])): ?>
                    <div class="text-red-600 mt-2 text-sm">
                        <?= htmlspecialchars(implode(', ', $messages['full-url']), ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="form-control mb-4">
                <?php
                $shortenedUrlElement->setLabelAttributes(['class' => 'label label-text text-gray-600']);
                $shortenedUrlElement->setLabel('Shortened URL')
                    ->setAttributes([
                        'class' => 'input input-bordered w-full placeholder-gray-500 placeholder:text-sm',
                        'placeholder' => 'Enter Shortened Url'
                    ]);
                echo $this->formLabel($shortenedUrlElement, $shortenedUrlElement->getLabel());
                ?>
                <?=
                $this->formElement($shortenedUrlElement);
                ?>
                <!-- Invalid shortened-url Errors-->
                <?php if (isset($messages['shortened-url'])): ?>
                    <div class="text-red-600 mt-2 text-sm">
                        <?= htmlspecialchars(implode(', ', $messages['shortened-url']), ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="form-control mb-4">
                <?php
                $commentsElement->setLabelAttributes(['class' => 'label label-text text-gray-600']);
                $commentsElement->setLabel('Comments')
                    ->setAttributes([
                        'class' => 'input input-bordered w-full placeholder-gray-500 placeholder:text-sm',
                        'placeholder' => 'Enter Shortened Url'
                    ]);
                echo $this->formLabel($commentsElement, $commentsElement->getLabel());
                ?>
                <?=
                $this->formElement($commentsElement);
                ?>
                <!-- Invalid comments Errors-->
                <?php if (isset($messages['comments'])): ?>
                    <div class="text-red-600 mt-2 text-sm">
                        <?= htmlspecialchars(implode(', ', $messages['comments']), ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>
            </div>
            <?=  $this->formElement($csrfElement); ?>
            <div class="form-control mt-4">
                <button type="submit" class="btn btn-primary w-full bg-blue-500 hover:bg-blue-600 text-white">
                    <?= $this->formElement($submitElement); ?>
                </button>
            </div>
            <?= $this->form()->closeTag($shortenedUrlForm); ?>
            </div>
        </div>
    </div>
</div>