
<div class="w-full">
    <div class="mx-auto px-0 w-full">
        <?php include __DIR__ . '/../../partials/top_nav_bar_menu_logged_out.phtml'; ?>
    </div>
</div>
<div class="flex">
    <!-- dashboard -->
    <?php
    include __DIR__.'/../../partials/user_sidebar_dashboard.phtml';
    ?>
    <div class="flex-1">
        <div class="min-h-screen  items-center justify-center mt-10">
            <h2 class="text-2xl font-bold mb-4 text-center text-gray-900">Create: URL Shortener Form</h2>
            <?php $shortenedUrl = $this->shortenedUrl; ?>
            <div class="max-w-4xl mx-auto mt-10 p-6 bg-white rounded-lg shadow-md">
                <h3 class="font-bold text-lg text-yellow-600 mb-4">Are you sure you want to delete this URL?</h3>
                <p class="py-3 text-gray-600">
                    <span class="font-bold">Short Description:</span> <span id="modal-short-description"><?= $shortenedUrl->getDescription() ?></span>
                </p>
                <p class="py-3 text-gray-600">
                    <span class="font-bold">Full URL:</span> <span id="modal-fullUrl"><?= $shortenedUrl->getFullUrl() ?></span>
                </p>
                <p class="py-3 text-gray-600">
                    <span class="font-bold">Shortened URL:</span> <span id="modal-shortened-url"><?= $shortenedUrl->getShortenedUrl() ?></span>
                </p>
                <p class="text-sm text-gray-500 mt-4">
                    Note: Later if you decide, you can restore the shortened link from the trash.
                </p>
                <div class="flex justify-end mt-6">
                    <a href="/shortenedurls/delete/<?= $this->shortenedUrl->getId()?>/confirmdelete">
                        <button id="url-submit" class="btn bg-yellow-500 text-white hover:bg-yellow-700 mr-2 px-6 py-2">
                            Submit
                        </button>
                    </a>
                    <a id="cancel" href="#" class="btn px-6 py-2 ml-4">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</div>




















