
<?php

$shortenedUrlForm = $this->shortenedUrlForm;

$shortenedUrlForm->getAttributes([
    'class'=>'form-control needs-validation novalidate',
    'style'=>'display:contents'
]);

$descriptionElement = $shortenedUrlForm->get('description');
$fullUrlElement = $shortenedUrlForm->get('full-url');
$shortenedUrlElement = $shortenedUrlForm->get('shortened-url');
$commentsElement = $shortenedUrlForm->get('comments');

$csrfElement = $shortenedUrlForm->get('shortened_url_csrf');

if($this->scenario == "edit"){

    $user = $this->user;
    $fullUrlElement->setValue( $this->shortenedUrl->getFullUrl());
    $shortenedUrlElement->setValue( $this->shortenedUrl->getShortenedUrl());
    $descriptionElement->setValue( $this->shortenedUrl->getDescription());
    $commentsElement->setValue( $this->shortenedUrl->getComments());
    /*$statusTypesElement->setValue( $this->shortenedUrl->getStatus());*/
}

$submitElement = $shortenedUrlForm->get('shortened-url-submit');
$shortenedUrlForm->prepare();
?>

<div class="w-full">
    <div class="mx-auto px-0 w-full">
        <?php include __DIR__ . '/../../partials/top_nav_bar_menu_logged_out.phtml'; ?>
    </div>
</div>
<div class="flex">
    <!-- dashboard -->
    <?php  
    include __DIR__.'/../../partials/user_sidebar_dashboard.phtml';
    ?>
    <div class="flex-1">
    <div class="min-h-screen  items-center justify-center mt-10">
        <div class="w-full max-w-3xl mx-auto bg-white rounded-lg shadow-lg p-6">
            <h2 class="text-2xl font-bold mb-4 text-center text-gray-900">Edit: URL Shortener Form</h2>
            
                <!-- Prepare messaages-->
                <?php 
                    $generalErrorMessage = $errorMessages = null;
                    $generalSuccessMessage = null;
                    if($this->messageType =="error")
                    {
                        if(isset($this->message))
                            $generalErrorMessage = $this->message;
                        if(isset($this->messages)){
                            $generalErrorMessage = 'There are error message(s) please check respective fields below, correct and resubmit the form.';
                            $errorMessages = $this->messages;
                        }

                    }else if($this->messageType =="success"){ 
                        if(isset($this->message))
                        $generalSuccessMessage = $this->message;
                    }
                    
                ?>

                 <!-- Display messaages-->

                <!-- Display error messaages-->

                <?php if ($this->messageType == 'error') {?>
                <div class="mb-4 p-4 text-red-700 bg-red-100 border border-red-400 rounded">
                    <?= htmlspecialchars($generalErrorMessage, ENT_QUOTES, 'UTF-8') ?>
                </div>

                <!-- Display success messaages-->
                <?php } else if ($this->messageType == 'success'){?>
                    <div class="mb-4 p-4 text-green-700 bg-green-100 border border-green-400 rounded">
                    <?= htmlspecialchars($generalSuccessMessage, ENT_QUOTES, 'UTF-8') ?>
                </div>
                <?php } ?>

                 <!-- Display csrf messaage-->
                <?php  if(isset($errorMessages)) if ($errorMessages['shortened_url_csrf']):?>

                    <div class="mb-4 p-4 text-red-700 bg-red-100 border border-red-400 rounded">
                        <?= htmlspecialchars(implode(', ', $errorMessages['shortened_url_csrf']), ENT_QUOTES, 'UTF-8') ?>
                    </div>

                <?php endif; ?>

            <!-- Display Form-->
            <?= $this->form()->openTag($shortenedUrlForm); ?>

            <div class="form-control mb-4">
                <?php
                $descriptionElement->setLabelAttributes(['class' => 'label label-text text-gray-600']);
                $descriptionElement->setLabel('Short Description')
                    ->setAttributes([
                        'class' => 'input input-bordered w-full placeholder-gray-500 placeholder:text-sm',
                        'placeholder' => 'Enter Shortened Url'
                    ]);
                echo $this->formLabel($descriptionElement, $descriptionElement->getLabel());
                ?>
                <?=
                $this->formElement($descriptionElement);
                ?>
                <!-- Invalid description Errors-->
                <?php if (isset($errorMessages['description'])): ?>
                    <div class="text-red-600 mt-2 text-sm">
                        <?= htmlspecialchars(implode(', ', $errorMessages['description']), ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="form-control mb-4">
               <?php
                $fullUrlElement->setLabelAttributes(['class' => 'label label-text text-gray-600']);
                $fullUrlElement->setLabel('Full URL')
                    ->setAttributes([
                        'class' => 'input input-bordered w-full placeholder-gray-500 placeholder:text-sm',
                        'placeholder' => 'Enter Full URL'
                    ]);
                echo $this->formLabel($fullUrlElement, $fullUrlElement->getLabel());
                ?>
                <?=
                $this->formElement($fullUrlElement);
                ?>
                <!-- Invalid full-url Errors-->
                <?php if (isset($errorMessages['full-url'])): ?>
                    <div class="text-red-600 mt-2 text-sm">
                        <?= htmlspecialchars(implode(', ', $errorMessages['full-url']), ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="form-control mb-4">
                <?php
                $shortenedUrlElement->setLabelAttributes(['class' => 'label label-text text-gray-600']);
                $shortenedUrlElement->setLabel('Shortened URL')
                    ->setAttributes([
                        'class' => 'input input-bordered w-full placeholder-gray-500 placeholder:text-sm',
                        'placeholder' => 'Enter Shortened Url'
                    ]);
                echo $this->formLabel($shortenedUrlElement, $shortenedUrlElement->getLabel());
                ?>
                <?=
                $this->formElement($shortenedUrlElement);
                ?>
                <!-- Invalid shortened-url Errors-->
                <?php if (isset($errorMessages['shortened-url'])): ?>
                    <div class="text-red-600 mt-2 text-sm">
                        <?= htmlspecialchars(implode(', ', $errorMessages['shortened-url']), ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="form-control mb-4">
                <?php
                $commentsElement->setLabelAttributes(['class' => 'label label-text text-gray-600']);
                $commentsElement->setLabel('Comments')
                    ->setAttributes([
                        'class' => 'input input-bordered w-full placeholder-gray-500 placeholder:text-sm',
                        'placeholder' => 'Enter Shortened Url'
                    ]);
                echo $this->formLabel($commentsElement, $commentsElement->getLabel());
                ?>
                <?=
                $this->formElement($commentsElement);
                ?>
                <!-- Invalid comments Errors-->
                <?php if (isset($errorMessages['comments'])): ?>
                    <div class="text-red-600 mt-2 text-sm">
                        <?= htmlspecialchars(implode(', ', $errorMessages['comments']), ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>
            </div>
            <?=  $this->formElement($csrfElement); ?>
            <div class="form-control mt-4">
                <button type="submit" class="btn btn-primary w-full bg-blue-500 hover:bg-blue-600 text-white rounded-full">
                    <?= $this->formElement($submitElement); ?>
                </button>
            </div>
            <?= $this->form()->closeTag($shortenedUrlForm); ?>
            </div>
        </div>
    </div>
</div>