<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="flex">
    <!-- Central Panel -->
    <?php
    include __DIR__.'/../../partials/user_sidebar_dashboard.phtml';
    ?>
    <!-- Main Content -->
    <div class="flex-1 p-10">

        <div class=" mx-auto px-4 max-w-full mt-14 items-center"  style="min-width: 90%;">
            <!-- Success Message Display -->
            <?php if(!empty($this->messageType)&& $this->messageType) { ?>
                <div class="items-center justify-start mb-14 flex">
                    <div class="text-left flex items-center bg-green-500 p-4 rounded-lg w-full">
                        <i class="fa fa-info-circle fa-2x mr-3"></i>
                        <span class="flex-grow my-auto text-lg w-full"><?= $this->message ?></span>
                        <i onclick="this.parentElement.style.display='none'" class="fa fa-remove  mr-3"></i>

                    </div>
                </div>


            <?php } ?>

            <div id="inner" class=" shadow-lg rounded-lg overflow-hidden items-center bg-white ">
                <div class="px-6 py-4 text-gray-800 flex justify-between items-center">
                    <div class="text-left">
                        <h3 class="text-xl font-semibold text-blue-700">Deleted Shortened URLs</h3>
                    </div>
                    <div class="flex items-center space-x-4">
                        
                        <!-- back to main list of urls -->
                        <a href="/shortenedurls" class="text-blue-700 hover:text-gray-700">
                            <i class="fa fa-backward m-3 fa-font" ></i>
                        </a>
                    </div>
                </div>

                <div class="overflow-x-auto text-center mx-2">
                    <table class="w-full min-w-[800px]  bg-gray-800 border-collapse border border-gray-300 mb-3 shadow-md rounded-lg overflow-hidden">
                        <thead class="bg-blue-700 text-white">
                        <tr>
                            <th class="px-4 py-2 text-left">Description</th>
                            <th class="px-4 py-2 text-left">Shortened URL</th>
                            <th class="px-4 py-2 text-left">Full URL</th>
                            <th class="px-4 py-2 text-left">Status</th>
                            <th class="px-4 py-2 text-left">Comments</th>
                            <th class="px-4 py-2 text-left">Created</th>
                            <th class="px-4 py-2 text-left">Modified</th>
                            <th class="px-4 py-2 text-left">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $urls = $this->shortenedUrls; if(!is_null($urls)) foreach ($urls as $url) { ?>
                            <tr class="bg-white border-b hover:bg-gray-300 text-gray-800 text-left">
                                <td class="px-4 py-2 "><?= $url->getDescription()?></td>
                                <td class="px-4 py-2"><?= $url->getShortenedUrl()?></td>
                                <td class="px-4 py-2"><?= $url->getFullUrl()?></td>
                                <td class="px-4 py-2"><?= $url->getStatus()?></td>
                                <td class="px-4 py-2"><?= $url->getComments()?></td>
                                <td class="px-4 py-2"><?= $url->getCreated()->format('Y-m-d H:i:s')?></td>
                                <td class="px-4 py-2"><?= $url->getModified()->format('Y-m-d H:i:s')?></td>
                                <td class="px-4 py-2">
                                    <!--Restore Action  -->
                                    <div>
                                        <a href='/shortenedurls/restore/<?= $url->getId()?>'>
                                            <span data-bs-toggle="tooltip" title="Edit Shortened Url">
                                                <i class="fa fa-undo m-3 fa-font text-blue-700"></i>
                                            </span>
                                        </a>
                                    </div>

                                </td>
                            </tr>
                        <?php } ?>
                        <!-- Repeat for more rows -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

