<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="min-h-screen">
    <div class="w-full">

            <?php include __DIR__ . '/../../partials/top_nav_bar_menu_logged_out.phtml'; ?>

    </div>

    <div class="flex">
        <!-- Central Panel -->
        <?php
        include __DIR__.'/../../partials/user_sidebar_dashboard.phtml';
        ?>
        <!-- Main Content -->
        <div class="flex-1 p-10">

            <div class=" mx-auto px-4 max-w-full mt-14 items-center"  style="min-width: 90%;">
                <!-- Success Message Display -->
                <?php if(!empty($this->messageType)&& $this->messageType) { ?>
                    <div class="items-center justify-start mb-14 flex">
                        <div class="text-left flex items-center bg-green-500 p-4 rounded-lg w-full">
                            <i class="fa fa-info-circle fa-2x mr-3"></i>
                            <span class="flex-grow my-auto text-lg w-full"><?= $this->message ?></span>
                            <i onclick="this.parentElement.style.display='none'" class="fa fa-remove  mr-3"></i>

                        </div>
                    </div>


                <?php } ?>

                <div id="inner" class=" shadow-lg rounded-lg overflow-hidden items-center bg-white ">
                    <div class="px-6 py-4 text-gray-800 flex justify-between items-center">
                        <div class="text-left">
                            <h3 class="text-xl font-semibold text-blue-700">Shortened URLs</h3>
                        </div>
                        <div class="flex items-center space-x-4">
                            <!-- 
                            <nav aria-label="Page navigation">
                                <ul class="inline-flex -space-x-px">
                                    <li>
                                        <a href="#" class="px-3 py-2 ml-0 leading-tight text-blue-700 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700">
                                            <i class="fa fa-chevron-left" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="px-3 py-2 leading-tight text-blue-700 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700">1</a>
                                    </li>

                                    <li>
                                        <a href="#" class="px-3 py-2 leading-tight text-blue-700 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700">
                                            <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav> -->
                            <!-- Plus icon -->
                            <a href="/shortenedurls/create" class="hover:text-gray-700 text-blue-700 ">
                                <i class="fa fa-plus m-3 fa-font"></i>
                            </a>
                            <!-- Trash icon -->
                            <a href="/shortenedurls/listTrash" class="text-blue-700 hover:text-gray-700">
                                <i class="fa fa-plus fa fa-trash m-3 fa-font" ></i>
                            </a>
                        </div>
                    </div>

                    <div class="overflow-x-auto text-center mx-2">
                        <table class="w-full min-w-[800px]  bg-gray-800 border-collapse border border-gray-300 mb-3 shadow-md rounded-lg overflow-hidden">
                            <thead class="bg-blue-700 text-white">
                            <tr>
                                <th class="px-4 py-2 text-left">Description</th>
                                <th class="px-4 py-2 text-left">Shortened URL</th>
                                <th class="px-4 py-2 text-left">Full URL</th>
                                <th class="px-4 py-2 text-left">Status</th>
                                <th class="px-4 py-2 text-left">Comments</th>
                                <th class="px-4 py-2 text-left">Created</th>
                                <th class="px-4 py-2 text-left">Modified</th>
                                <th class="px-4 py-2 text-left">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $urls = $this->shortenedUrls; if(!is_null($urls)) foreach ($urls as $url) { ?>
                                <tr class="bg-white border-b hover:bg-gray-300 text-gray-800 text-left">
                                    <td class="px-4 py-2 "><?= $url->getDescription()?></td>
                                    <td class="px-4 py-2"><?= $url->getShortenedUrl()?></td>
                                    <td class="px-4 py-2"><?= $url->getFullUrl()?></td>
                                    <td class="px-4 py-2"><?= $url->getStatus()?></td>
                                    <td class="px-4 py-2"><?= $url->getComments()?></td>
                                    <td class="px-4 py-2"><?= $url->getCreated()->format('Y-m-d H:i:s')?></td>
                                    <td class="px-4 py-2"><?= $url->getModified()->format('Y-m-d H:i:s')?></td>
                                    <td class="px-4 py-2">
                                        <!--View Action  -->
                                        <div>
                                            <a href='/shortenedurls/view/<?= $url->getId()?>'>
                                                <span data-bs-toggle="tooltip" title="View document">
                                                    <i class="fa fa-eye m-3 fa-font text-blue-700"></i>
                                                </span>
                                            </a>
                                        </div>
                                        <!--Edit Action  -->
                                        <div>
                                            <a href='/shortenedurls/edit/<?= $url->getId()?>'>
                                                <span data-bs-toggle="tooltip" title="Edit document">
                                                    <i class="fa fa-edit m-3 fa-font text-blue-700"></i>
                                                </span>
                                            </a>
                                        </div>
                                        <!--Delete Action  -->
                                        <div>
                                           <!-- <a href="#my_modal_8" class="btn">open modal</a>-->
                                            <a id="deleteButton" href="shortenedurls/delete/<?= $url->getId()?>/showdialog" class="delete-url"
                                                    data-description='<?= $url->getDescription()?>'
                                                   data-fullUrl='<?= $url->getFullUrl()?>'
                                                   data-shortened-url='<?= $url->getShortenedUrl()?>'
                                                   data-url-id='<?= $url->getId()?>'>
                                              <span class="tooltip tooltip-bottom text-blue-700" data-tip="Delete document">
                                                <i class="fa fa-remove m-3" style="font-size: 20px !important;"></i>
                                              </span>
                                            </a>
                                        </div>
                                        <!--Visit Target -->
                                        <div>
                                            <a href="shortenedurls/redirect/<?= $url->getId()?>">
                                              <span class="tooltip tooltip-bottom text-blue-700" data-tip="Redirect to Full">
                                                <i class="fa fa-bullseye m-3" style="font-size: 20px !important;"></i>
                                              </span>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                            <!-- Repeat for more rows -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

