
<?php

$shortenedUrlObj = $this->shortenedUrl;
$description = $shortenedUrlObj->getDescription();
$fullUrl = $shortenedUrlObj->getFullUrl();
$shortenedUrl = $shortenedUrlObj->getShortenedUrl();
$comments = $shortenedUrlObj->getComments();

$created = $shortenedUrlObj->getCreated();
$modified = $shortenedUrlObj->getModified();

?>

<div class="w-full">
    <div class="mx-auto px-0 w-full">
        <?php include __DIR__ . '/../../partials/top_nav_bar_menu_logged_out.phtml'; ?>
    </div>
</div>
<div class="flex">
    <!-- dashboard -->
    <?php
    include __DIR__.'/../../partials/user_sidebar_dashboard.phtml';
    ?>
    <div class="flex-1">
        <div class="min-h-screen  items-center justify-center mt-10">
            <div class="w-full max-w-3xl mx-auto bg-white rounded-lg shadow-lg p-6">
                <div class="text-left">
                    <h3 class="text-xl font-semibold text-blue-700 mb-5">View: Shortened URL</h3>
                </div>
                    <div class="mb-4">
                        <label class="block text-gray-700 text-sm font-bold mb-2">Description:</label>
                        <p class="text-gray-900 text-base"><?=  $description?></p>
                    </div>
                    <div class="mb-4">
                        <label class="block text-gray-700 text-sm font-bold mb-2">Full URL:</label>
                        <p class="text-gray-900 text-base"><?=  $fullUrl?></p>
                    </div>
                    <div class="mb-4">
                        <label class="block text-gray-700 text-sm font-bold mb-2">Shortened URL:</label>
                        <p class="text-blue-500 text-base break-all"><?=  $shortenedUrl?></p>
                    </div>
                    <div class="mb-4">
                        <label class="block text-gray-700 text-sm font-bold mb-2">Comments:</label>
                        <p class="text-gray-900 text-base"><?=  $comments ?></p>
                    </div>
                   
                    <div class="mb-4">
                        <label class="block text-gray-700 text-sm font-bold mb-2">Created:</label>
                        <p class="text-gray-900 text-base"><?=  $created->format('Y:m:d')?></p>
                    </div>
                    <div class="mb-4">
                        <label class="block text-gray-700 text-sm font-bold mb-2">Modified:</label>
                        <p class="text-gray-900 text-base"><?=  $modified->format('Y:m:d')?></p>
                    </div>
            </div>
        </div>
    </div>
</div>