<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Global Tickets')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/css/app.css">
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/daisyui@1.14.0/dist/full.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Global Tickets Assessment</title>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <?= $this->content ?>
        <?php
        include __DIR__.'/../partials/footer.phtml';
        ?>
        <script>
            function setTheme(theme) {
                document.documentElement.setAttribute('data-theme', theme);
            }
        </script>
        <script src="/js/app.js"></script>

        <script src="https://cdn.tailwindcss.com"></script>
    </body>
</html>
