
<div class="min-h-screen">
    <div class="w-full">

        <?php include __DIR__ . '/../../partials/top_nav_bar_menu_logged_out.phtml'; ?>

    </div>
    <div class="flex">
        <!-- dashboard -->
        <?php
        include __DIR__.'/../../partials/user_sidebar_dashboard.phtml';
        ?>
        <!-- Main Content -->
        <div class="flex-1 p-10">

            <?php if(!empty($this->messageType)&& $this->messageType=='info') { ?>
                <div id="alert-container" class=" mx-auto px-4 max-w-full mt-14 items-left"  style="min-width: 90%;">
                    <div class="alert alert-info shadow-lg flex items-left">
                        <span class="text-lg"><i class="fa fa-info-circle fa-2x mr-3 text-blue-600"></i><?= $this->message ?></span>
                        <button type="button" class="close bg-transparent border-0 text-2xl font-semibold" aria-label="Close" onclick="document.getElementById('alert-container').style.display='none'">x</button>

                    </div>

                </div>
            <?php } ?>

            <div class=" mx-auto px-4 max-w-full mt-14 items-center"  style="min-width: 90%;">
                <div id="inner" class=" shadow-lg rounded-lg overflow-hidden items-center bg-white ">
                    <div class="px-6 py-4 text-gray-800 flex justify-between items-center">
                        <div class="text-left">
                            <h3 class="text-xl font-semibold text-blue-700">Shortened URLs</h3>
                        </div>
                        <div class="flex items-center space-x-4">
                            <!-- Pagination bar -->
                            <nav aria-label="Page navigation">
                                <ul class="inline-flex -space-x-px">
                                    <li>
                                        <a href="#" class="px-3 py-2 ml-0 leading-tight text-blue-700 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700">
                                            <i class="fa fa-chevron-left" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="px-3 py-2 leading-tight text-blue-700 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700">1</a>
                                    </li>

                                    <li>
                                        <a href="#" class="px-3 py-2 leading-tight text-blue-700 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700">
                                            <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                            <!-- Plus icon -->
                            <a href="#" class="hover:text-gray-700 text-blue-700 ">
                                <i class="fa fa-plus m-3 fa-font"></i>
                            </a>
                            <!-- Trash icon -->
                            <a href="#" class="text-blue-700 hover:text-gray-700">
                                <i class="fa fa-plus fa fa-trash m-3 fa-font" ></i>
                            </a>
                        </div>
                    </div>
                    <div class="overflow-x-auto text-center mx-2">
                        <table class="w-full min-w-[800px]  bg-gray-800 border-collapse border border-gray-300 mb-3 shadow-md rounded-lg overflow-hidden">
                            <thead class="bg-blue-700 text-white">
                            <tr>
                                <th class="px-4 py-2 text-left">Username</th>
                                <th class="px-4 py-2 text-left">First Name</th>
                                <th class="px-4 py-2 text-left">Middle Name</th>
                                <th class="px-4 py-2 text-left">Last Name</th>
                                <th class="px-4 py-2 text-left">Email</th>
                                <th class="px-4 py-2 text-left">Status</th>
                                <th class="px-4 py-2 text-left">Created</th>
                                <th class="px-4 py-2 text-left">Modified</th>
                                <th class="px-4 py-2 text-left">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if(!is_null($this->users)) foreach ($this->users as $user) { ?>
                                <tr class="bg-white border-b hover:bg-gray-300 text-gray-800 text-left">
                                    <td class="px-4 py-2 "><?= $user->getUserName()?></td>
                                    <td class="px-4 py-2"><?= $user->getFirstName()?></td>
                                    <td class="px-4 py-2"><?= $user->getMiddleName()?></td>
                                    <td class="px-4 py-2"><?= $user->getLastName()?></td>
                                    <td class="px-4 py-2"><?= $user->getEmail()?></td>
                                    <td class="px-4 py-2"><?= $user->getState()?></td>
                                    <td class="px-4 py-2"><?= $user->getCreated()->format('Y-m-d H:i:s')?></td>
                                    <td class="px-4 py-2"><?= $user->getModified()->format('Y-m-d H:i:s')?></td>
                                    <td class="px-4 py-2">
                                        <!--View Action  -->
                                        <div>
                                            <a href="/users/view/40">
                                                <span data-bs-toggle="tooltip" title="Edit document">
                                                    <i class="fa fa-edit m-3 fa-font text-blue-700"></i>
                                                </span>
                                            </a>
                                        </div>
                                        <!--Edit Action  -->
                                        <div>
                                            <a href="/shortenedurls/edit/40">
                                                <span data-bs-toggle="tooltip" title="Edit document">
                                                    <i class="fa fa-edit m-3 fa-font text-blue-700"></i>
                                                </span>
                                            </a>
                                        </div>
                                        <!--Delete Action  -->
                                        <div>
                                            <a href="" >
                                                <span data-bs-toggle="tooltip" title="Delete document" >
                                                    <i class="fa fa-remove m-3 text-blue-700" style="font-size:20px;"></i>
                                                </span>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                            <!-- Repeat for more rows -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

